### PR TITLE
Alias creation bug fix

### LINKED ISSUE #370: Unable to access FTS data
I tried to perform several distinct queries on FTS data (query numbers 789, 790 and 791) but in every case they come up empty. Not sure what the issue is there.
The data search on the FTS website however also seems stuck and does not spit out data for me - might be related, not sure. 

Wondering, if the data pull from FTS is indeed broken (potentially due to issues on their side) - do we have frozen datasets from past data pulls we could use instead?

### PR DESCRIPTION
**Pull request by ThatcherK**
This branches handles the different stages involved in alias creation as well as a few minor bug fixes

### CODE REVIEW

File: frontend/src/pages/QueryBuilder/QueryBuilder.tsx [hunk 1]
```diff
@@ -173,17 +173,29 @@ const QueryBuilder: FunctionComponent<QueryBuilderProps> = (props) => {
           data,
         })
         .then((response: AxiosResponse<Operation>) => {
-          if (response.status === 200 || response.status === 201) {
-            props.actions.operationSaved(true);
-            if (preview) {
-              props.history.push(`/queries/data/${response.data.id}/`);
-            } else {
-              props.history.push('/');
+          if (response.data.alias_creation_status !== 'p') {
```
Comment (edwinmp) [inline frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: This shouldn't be here ... it's not possible that this could happen since if the code runs without interruption, it can only have two status ... `d` & `e` (probably only `d`)... So in addition to the error check on line 191, this check should also be done in `setActiveOperationByID` (I think), to be run when the user first opens the query builder to edit an existing operation. i.e. `if (operation.alias_creation_status !== 'd')`. Alternatively, u can have a `useEffect` that watches for changes in `props.activeOperation`, then checks the alias creation status.

File: frontend/src/types/operations.ts [hunk 2]
```diff
@@ -17,6 +17,7 @@ export interface Filters<T = Filter[] | ErroredFilter[]> {
   filters: T;
 }
 export interface Operation {
+  alias_creation_status: string;
```
Comment (edwinmp) [inline frontend/src/types/operations.ts]: Give it a more specific type i.e. `'d' | 'e' | 'p'`

**Review by edwinmp — CHANGES_REQUESTED** [review]
🎩

**Comment by edwinmp** [comment]
Your branch is behind develop by more than a few commits, and since you're going to need to add end-to-end testing for this feature, you'll need code that's on develop. So please rebase and push (you'll have to force push). If you're not confident with rebasing, create a new branch off `fix/alias`, do the rebase in there and push. Can review that first before u try it on this branch.

File: frontend/src/pages/QueryBuilder/QueryBuilder.tsx (hunk 1 above)
Comment (ThatcherK) [reply frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: Oh yes,this sounds more practical

File: frontend/src/pages/QueryBuilder/QueryBuilder.tsx [hunk 3]
```diff
@@ -102,6 +102,11 @@ const QueryBuilder: FunctionComponent<QueryBuilderProps> = (props) => {
   const setActiveOperationByID = (id: string) => {
     const operation = props.operations.find((ope) => ope.get('id') === parseInt(id, 10));
     if (operation) {
+      if (operation.get('alias_creation_status') === 'p') {
```
Comment (edwinmp) [inline frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: Check `!== 'd'` ... I'd rather flag this for error events as well.

**Review by edwinmp — CHANGES_REQUESTED** [review]
As I said in a previous comment, you'll have to add Cypress tests to this. There's info in the READ me under end-to-end testing.

File: frontend/src/pages/QueryBuilder/QueryBuilder.tsx (hunk 3 above)
Comment (ThatcherK) [reply frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: This is not very clear

Comment (edwinmp) [reply frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: Very well ... replace this with:
`if (operation.get('alias_creation_status') !== 'd') {`

Comment (ThatcherK) [reply frontend/src/pages/QueryBuilder/QueryBuilder.tsx]: Okay

File: Dockerfile_pg_dev [hunk 4]
```diff
@@ -1,5 +1,5 @@
 # start with a base image
-FROM postgres:12.5
+FROM postgres:11
```
Comment (edwinmp) [inline Dockerfile_pg_dev]: Nope ... this may have fixed your issue but it'll break all ours. Upgrade your local postgres to the expected version instead. (soon to be version 13)

File: cypress.json [hunk 5]
```diff
@@ -1,5 +1,5 @@
 {
-  "baseUrl": "https://staging-ddw.devinit.org",
+  "baseUrl": "http://localhost/",
```
Comment (edwinmp) [inline cypress.json]: You need to be careful what you commit ... at the very least, review the files you stage before you commit them.

File: frontend/cypress/fixtures/users.json [hunk 6]
```diff
@@ -1,10 +1,10 @@
...
   {
     "id": 1,
-    "name": "Admin McAwesome",
-    "username": "admin@test.com",
-    "email": "admin@test.com",
-    "password": "Spp9k6i7",
+    "name": "Admin",
+    "username": "Admin",
+    "email": "admin@mail.com",
+    "password": "atwookimomo@23",
```
Comment (edwinmp) [inline frontend/cypress/fixtures/users.json]: This is going to break all tests on deployment ... instead of changing these to suit yours, why not create a user with the expected credentials. I mean, this didn't need to change at all really.

File: frontend/cypress/integration/queryBuilder.spec.js [hunk 7]
```diff
@@ -45,6 +45,19 @@ describe('The Query Builder', () => {
...
 
+  it('that encountered an error or interruption during alias creation shows a warning', () => {
+    // Mock datasets route
+    cy.fixture('datasets').then((datasets) => {
+      cy.intercept('api/datasets/mine/', datasets);
+    });
+
+    cy.visit('/');
+    cy.get('.p-0 div a').first().click({ force: true });
+    cy.get('.p-1').contains(
```
Comment (edwinmp) [inline frontend/cypress/integration/queryBuilder.spec.js]: These classes `p-0, p-1` are at high risk of changing, which will break your tests. I'd rather you add a testId to your elements.

File: frontend/cypress/integration/queryBuilder.spec.js [hunk 8]
```diff
@@ -45,6 +45,19 @@ describe('The Query Builder', () => {
     cy.get('.invalid-feedback').should('not.be.visible');
   });
 
+  it('that encountered an error or interruption during alias creation shows a warning', () => {
+    // Mock datasets route
+    cy.fixture('datasets').then((datasets) => {
+      cy.intercept('api/datasets/mine/', datasets);
+    });
```
Comment (edwinmp) [inline frontend/cypress/integration/queryBuilder.spec.js:72]: This was brilliant ...

**Review by edwinmp — CHANGES_REQUESTED** [review]

File: frontend/cypress/fixtures/users.json (hunk 6 above)
Comment (ThatcherK) [reply frontend/cypress/fixtures/users.json]: I was getting an unauthorized error

Comment (edwinmp) [reply frontend/cypress/fixtures/users.json]: I'm sure ... so create a user with the expected credentials, either via Django admin or with [createsuperuser](https://djangocentral.com/creating-super-user-in-django/) ... u only need the matching username & password.

**Comment by edwinmp** [comment]
Also, there's conflicts with `develop`, so you'll need to rebase.

**Review by edwinmp — APPROVED** [review]
Great work on this ... learned a few things myself.
